default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(requirements.in)$
        args: ["--ignore-case", "--unique"]
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.2.3"
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.149
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
