[tool.black]
target-version = ["py311"]

[tool.mypy]
ignore_missing_imports = true
python_version = "3.11"

[tool.ruff]
exclude = [
    '__pycache__',
    '.vscode',
]
extend-ignore = [
    "D203",
    "D212",
    "D213",
    "D214",
    "D215",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D413",
    "D415",
    "D416",
    "D417",
]
select = ["A", "B", "C", "D", "E", "F", "I", "W", "B9"]
target-version = "py311"
